"Traceback (most recent call last):\n  File \"/Users/terrylin/METPOL_AI/backend/server/api/routes.py\", line 91, in ask_question\n    Message.create(\n  File \"/Users/terrylin/METPOL_AI/backend/server/database.py\", line 220, in create\n    json.dumps(retrieved_chunks) if retrieved_chunks else None,\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/terrylin/.pyenv/versions/3.11.9/lib/python3.11/json/__init__.py\", line 231, in dumps\n    return _default_encoder.encode(obj)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/terrylin/.pyenv/versions/3.11.9/lib/python3.11/json/encoder.py\", line 200, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/terrylin/.pyenv/versions/3.11.9/lib/python3.11/json/encoder.py\", line 258, in iterencode\n    return _iterencode(o, 0)\n           ^^^^^^^^^^^^^^^^^\n  File \"/Users/terrylin/.pyenv/versions/3.11.9/lib/python3.11/json/encoder.py\", line 180, in default\n    raise TypeError(f'Object of type {o.__class__.__name__} '\nTypeError: Object of type ChunkResult is not JSON serializable\n"
